### ISSUE TITLE
Changing background on the fly affects highlight

### ISSUE THREAD

**Issue by sriramkswamy** [tweekmonster/local-indent.vim#2]
First off, I really really love this plugin.

I hate to be _that_ guy but the highlight doesn't work when I change the background. I have a theme that has both light and dark variants - [PaperColor](https://github.com/NLKNguyen/papercolor-theme). I usually start with the light version during the day and switch to the dark one in the night by just changing `set background` to `dark`.

The highlight works in both light and dark variants IF I start Vim in light or dark. It fails to highlight when I switch the background on the fly in either cases.

Thanks again for this plugin!

**Comment by tweekmonster** [comment]
Always be that guy.  How else is it going to get fixed?

Anyways, it's fixed.  But, that just fixes the default highlighting.  Switching backgrounds/colorschemes might reset the existing highlights, so if you're using a custom highlight color, you should have something like this in your vimrc so that it's set when there is a change:

``` vim
autocmd ColorScheme * highlight LocalIndentGuide ...
```
