### ISSUE TITLE
Option to trigger on `CursorHold` instead of `CursorMoved`

### ISSUE THREAD

**Issue by bimlas** [tweekmonster/local-indent.vim#3]
It works like a charm but can be slow on long blocks. Using `CursorHold,CursorHoldI` can solve this problem (and therefore `TextChanged,TextChangedI` triggers not needed). Just think on it: if the user wants to know which block is "active", he/she stops moving for a bit. 

I could do the patch but I don't know how do you want to implement the "flag" for it (global variable/command line argument).

**Comment by tweekmonster** [comment]
I really don't like CursorHold for things like this, but I can't argue with performance issues.  Could you tell me how many lines was enough to cause a slowdown?  There might be a better way to fix the slow down, like not highlighting the first indent level since those should be obvious.  Another option I thought about was only scanning from `w0` to `w$` which is much faster, but would cause the highlight to become stale if the window scrolled without moving the cursor.

Another thing that comes to mind is that the abuse of [`matchaddpos()` is also contributing to the slowdown](https://git.io/vgFe2).  Would you be able to change that line to `if 0` and see if that improves the speed for you?

**Comment by tweekmonster** [comment]
I'm going ahead with only scanning visible lines.  I did a test with 3000 lines of alternating, and it seems to perform well.  If you still think CursorHold would be better, I can look into it.  Also, feel free to send a PR.  I think a global flag would be suitable for changing the autocmds since that would be a broad user preference and not per-buffer/filetype thing.

**Comment by bimlas** [comment]
Great work: it become way more faster! :+1: Now I don't need the `CursorHold` feature, thanks!
